name: Build and Deploy
on: 
  push:
    branches:
      - main  # 或者你的主分支
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # 或者更低版本

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '7.0.0'  # 指定 pnpm 的版本，可以根据需要调整

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build the site
        run: |
          pnpm run build

      - name: Deploy to GitHub Pages
        uses: jenkey2011/vuepress-deploy@v1
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: CosmosTan/techblog
          TARGET_BRANCH: gh_pages
          BUILD_SCRIPT: pnpm run build
          BUILD_DIR: docs/.vuepress/dist
