name: Build and Deploy

on: 
  push:
    branches:
      - main  # 或者你的主分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # 或者选择 '14' 或其他兼容版本

      - name: Set NODE_OPTIONS to use OpenSSL legacy provider (for Node.js v17+)
        run: echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV  # 如果使用 Node.js v17+

      - name: Install dependencies
        run: |
          yarn install

      - name: Build the site
        run: |
          yarn build

      - name: Deploy to GitHub Pages
        uses: jenkey2011/vuepress-deploy@v1
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: CosmosTan/techblog
          TARGET_BRANCH: gh_pages
          BUILD_SCRIPT: yarn && yarn build
          BUILD_DIR: docs/.vuepress/dist
